version: "3.9"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    environment:
      CLICKHOUSE_DB: events
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: event
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - chdata:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  app:
    build: .
    environment:
      CLICKHOUSE_ADDRS: clickhouse:9000
      CLICKHOUSE_DB: events
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: event
      HTTP_PORT: :8080
    ports:
      - "8080:8080"
    depends_on:
      - clickhouse
    # Run migrations manually before starting the app in production
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  load-tester:
    build: ./load-tester
    container_name: load-tester
    # Prevent the container from exiting immediately
    command: tail -f /dev/null 
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - app


volumes:
  chdata:
