version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: event
      POSTGRES_PASSWORD: event
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  app:
    build: .
    environment:
      DATABASE_URL: postgres://event:event@db:5432/events?sslmode=disable
      HTTP_PORT: :8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    # Run migrations manually before starting the app in production
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  load-tester:
    build: ./load-tester
    container_name: load-tester
    # Prevent the container from exiting immediately
    command: tail -f /dev/null 
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - app


volumes:
  pgdata:
